service: import-service
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  custom:
  environment:
    PRODUCTS_BUCKET: import-cahv
    REGION: us-east-1
  s3:
    import-cahv:
      name: import-cahv
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ReadObject'
          Resource:
            - 'arn:aws:s3:::import-cahv/*'

functions:
  importProductsFile:
    handler:  handlers/files/upload.upload
    url: true
    events:
      - httpApi:
          path: /import/{name}
          method: GET
  importFileParser:
    handler:  handlers/files/parser.parser      
    events:
      - s3:
          bucket: import-cahv
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          # Set to 'true' when using an existing bucket
          # Else the bucket will be automatically created
          existing: true
          # Optional, for forcing deployment of triggers on existing S3 buckets
          forceDeploy: true
resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: import-cahv
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ['*']
              Id: CORSRuleId1
              MaxAge: 3600
